#pragma once

#define EPERM         1
#define ENOENT        2
#define ESRCH         3
#define EINTR         4
#define EBADF         9
#define ECHILD       10
#define ENOMEM       12
#define EFAULT       14
#define ENOTDIR      20
#define EISDIR       21
#define EINVAL       22
#define ENFILE       23
#define EMFILE       24
#define ENOTTY       25
#define ENOSPC       28
#define ESPIPE       29
#define EROFS        30
#define ERANGE       34
#define ENAMETOOLONG 36
#define ENOSYS       38
#define EIO           5
#define EEXIST       17
#define EFBIG        27
#define ENOTEMPTY    39
#define EPIPE        32
#define ENOTSUP      95
#define ELOOP        40
